create extension if not exists postgis;

create table member
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    email         varchar(255) not null
        constraint ukmbmcqelty0fbrvxp1q58dn57t
            unique,
    nickname      varchar(255) not null,
    profile_image varchar(255),
    provider      varchar(255) not null
        constraint member_provider_check
            check ((provider)::text = ANY ((ARRAY ['GOOGLE'::character varying, 'KAKAO'::character varying])::text[])),
    provider_id   varchar(255) not null,
    username      varchar(255)
        constraint ukgc3jmn7c2abyo3wf6syln5t2i
            unique
);

create table couple
(
    id                      bigint generated by default as identity
        primary key,
    created_at              timestamp(6),
    updated_at              timestamp(6),
    couple_banner_image_url varchar(255),
    couple_start_date       date,
    couple_status           varchar(255) not null
        constraint couple_couple_status_check
            check ((couple_status)::text = ANY
                   ((ARRAY ['ACCEPTED'::character varying, 'WAITING'::character varying])::text[])),
    member_1                bigint       not null
        constraint ukj1x8ldg116jum1njamhphbee5
            unique
        constraint fk1hq7ry081dfogt4n1k5uu8toq
            references member,
    member_2                bigint       not null
        constraint ukki92gpwclrhfa4p7hs3b49j6a
            unique
        constraint fkolwxbrrbf46el6jghlkxw5gjj
            references member
);

create table course
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    course_description  varchar(1024) not null,
    course_negative     varchar(1024),
    course_positive     varchar(1024),
    course_rating       numeric(3, 1),
    course_region       varchar(128)  not null,
    course_tags         varchar(255),
    course_title        varchar(128),
    course_visit_date   date          not null,
    course_visit_member varchar(128)  not null,
    is_public           boolean       not null,
    scrap_count         integer       not null,
    view_count          integer       not null,
    member_id           bigint        not null
        constraint fkkcqry8au976fmoov49prx1212
            references member
);

create table couple_course_comment
(
    comment_type varchar(31) not null,
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    image_url    varchar(255),
    content      varchar(1000),
    course_id    bigint      not null
        constraint fkmilb71ogv4w6cxya4bhw1geco
            references course,
    member_id    bigint      not null
        constraint fkfgr5d9wkj9j0butq2fqop6xvu
            references member
);

create table course_comment
(
    id        bigint generated by default as identity
        primary key,
    content   varchar(255) not null,
    course_id bigint       not null
        constraint fki2x4qwjfqowv1gxbt2ybxo9il
            references public.course,
    member_id bigint       not null
        constraint fkei8xw2436hbcy2rxdx6m419p9
            references member
);

create table course_scrap
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    course_id  bigint not null
        constraint fke6vjt9csulywxp4587twh0x69
            references course,
    member_id  bigint not null
        constraint fkw32te5to51qn45dhrwf9tg65
            references member,
    constraint course_scrap_uk
        unique (member_id, course_id)
);

create table place_group
(
    id   bigint generated by default as identity
        primary key,
    code varchar(10) not null
        constraint uk3essrvc3m16kouyll6dmfabe7
            unique,
    name varchar(50) not null
);

create table place
(
    id                        bigint generated by default as identity
        primary key,
    created_at                timestamp(6),
    updated_at                timestamp(6),
    location                  geography(Point, 4326),
    pin_count                 bigint,
    place_category            varchar(255),
    place_name                varchar(255) not null,
    place_number_address      varchar(255),
    place_rating              numeric(3, 1),
    place_street_name_address varchar(255) not null,
    place_tags                varchar(255),
    place_url                 varchar(255),
    scrap_count               bigint       not null,
    place_group_id            bigint       not null
        constraint fkdnsc2gp0ebrv9s9a1t8n984w4
            references place_group
);

create table pin
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    pin_negative varchar(255) not null,
    pin_positive varchar(255) not null,
    pin_rating   numeric(3, 1),
    course_id    bigint       not null
        constraint fkk10of7nblwu0u7pi8c1rwm7ob
            references course,
    place_id     bigint       not null
        constraint fk3rieohd70jvm0333laein8ps9
            references place
);

create index idx_pin_place_id
    on pin (place_id);

create table pin_image
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    image_url  varchar(255) not null,
    pin_id     bigint
        constraint fk9euf7l8r3dqhjh77nqs3yilh0
            references pin
);

create index idx_pinimage_pin_id
    on pin_image (pin_id);

create index idx_place_location_gist
    on place using gist (location);

create table place_scrap
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    member_id  bigint not null
        constraint fk88k10ih5m3sejy3dc7nacvywq
            references member,
    place_id   bigint not null
        constraint fk87ohgw25843ed9w0io9k7yfm1
            references place,
    constraint place_scrap_uk
        unique (member_id, place_id)
);

create index idx_placescrap_member_id
    on place_scrap (member_id);

create index idx_placescrap_place_id
    on place_scrap (place_id);

create table tag_value
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        constraint ukoq1q6kqbxy7ehwj5cns0xj017
            unique
);

create table tag
(
    id             bigint generated by default as identity
        primary key,
    tag_group      varchar(20) not null
        constraint tag_tag_group_check
            check ((tag_group)::text = ANY
                   ((ARRAY ['ATMOSPHERE'::character varying, 'FACILITY'::character varying, 'FOOD_PRICE'::character varying, 'ETC'::character varying])::text[])),
    place_group_id bigint      not null
        constraint fkryegj50fm8n2366qeepvohh9c
            references place_group,
    tag_value_id   bigint      not null
        constraint fk7fnn62bi3j8vk2nq3h7xo8fr7
            references tag_value
);

create table pin_tag
(
    id     bigint generated by default as identity
        primary key,
    pin_id bigint not null
        constraint fkf6270xy9g8kby20ngjptttneg
            references pin,
    tag_id bigint not null
        constraint fk9nbsmli6177qnee88533be2xe
            references tag
);
